---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
  tags:
    - fail2ban
    - install

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: ansible_distribution == "CentOS" and not epel_repofile_result.stat.exists
  tags:
    - fail2ban
    - install

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: ansible_distribution == "CentOS" and not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - fail2ban
    - install
